name: brillo_sportz
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  device_preview: ^1.1.0
  dio: ^5.4.3+1
  email_validator: ^3.0.0
  equatable: ^2.0.5
  eva_icons_flutter: ^3.1.0
  flex_color_scheme: ^7.3.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_riverpod: ^2.5.1
  flutter_screenutil: ^5.9.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.0.10+1
  form_field_validator: ^1.1.0
  go_router: ^14.1.3
  intl: ^0.19.0
  jwt_decoder: ^2.0.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.4.0
  riverpod_annotation: ^2.3.5
  salomon_bottom_bar: ^3.3.2
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.1.0
dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/svgs/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsSemiBold.ttf
          weight: 600
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
        - asset: assets/fonts/PoppinsRegular.ttf
          weight: 400
        - asset: assets/fonts/PoppinsLight.ttf
          weight: 300
    - family: Mulish
      fonts:
        - asset: assets/fonts/MuliSemiBold.ttf
          weight: 600
